### ISSUE TITLE
Facebook Login Error - invalid key hash

### ISSUE THREAD

**Issue by sglee7744** [nice295/Health-Battle#1]
09-18 21:46:09.212 11304-11304/com.nice295.healthbattle D/FacebookLogin: facebook:onError
                                                                         Invalid key hash. The key hash oE8L+gN1Wl/7/0YgQMvGnpzjO7I= does not match any stored key hashes. Configure your app key hashes at http://developers.facebook.com/apps/1604785776481010
                                                                             at com.facebook.login.LoginManager.onActivityResult(LoginManager.java:190)
                                                                             at com.facebook.login.LoginManager$1.onActivityResult(LoginManager.java:159)
                                                                             at com.facebook.internal.CallbackManagerImpl.onActivityResult(CallbackManagerImpl.java:82)
                                                                             at com.nice295.healthbattle.FacebookLoginActivity.onActivityResult(FacebookLoginActivity.java:127)
                                                                             at android.app.Activity.dispatchActivityResult(Activity.java:7137)
                                                                             at android.app.ActivityThread.deliverResults(ActivityThread.java:4921)
                                                                             at android.app.ActivityThread.handleSendResult(ActivityThread.java:4968)
                                                                             at android.app.ActivityThread.access$1600(ActivityThread.java:222)
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1849)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                             at android.os.Looper.loop(Looper.java:158)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:7229)
                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by nice295** [comment]
내가 만든 키가 다른 개발자에게는 안 먹히나?!
